#!/bin/bash

# this DIRECTORY should contain "cyclone.jar" file
CYCLONE_PATH="/path/to/dir/of/Cyclone"

if [ ! -d "$CYCLONE_PATH" ]; then
  echo "Can not locate directory of cyclone."
  exit 1
fi


# Linux
export LD_LIBRARY_PATH=$CYCLONE_PATH
# MacOS
export DYLD_LIBRARY_PATH=$CYCLONE_PATH

echo "option-generation=\"SMT2\";" > $1_gen.cyclone
cat $1 >> $1_gen.cyclone
# sed -i '/option-trace/d' $1_gen.cyclone
java -Xss512m -Xms12g -jar "$CYCLONE_PATH/cyclone.jar" $1_gen.cyclone
if [ -e "$1_gen.cyclone.smt2.dump" ]; then
  mv $1_gen.cyclone.smt2.dump $1_gen.smt2
  sed -i 's/simplify/assert/g' $1_gen.smt2
  echo "" >> $1_gen.smt2
  echo "(check-sat)" >> $1_gen.smt2
  echo "generated: $1_gen.smt2"
  rm -f $1_gen.cyclone
fi
