#!/bin/bash

D=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# this DIRECTORY should contain "cyclone.jar" file
CYCLONE_PATH="$D/cyclone1359"

java -jar "$CYCLONE_PATH/cyclone.jar" $1
