#!/bin/bash

D=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# this DIRECTORY should contain "cyclone.jar" file
CYCLONE_PATH="$D/cyclone1359"

echo "option-generation=\"SMT2\";" > $1_gen.cyclone
cat $1 >> $1_gen.cyclone

# sed -i '/option-trace/d' $1_gen.cyclone
java -jar "$CYCLONE_PATH/cyclone.jar" $1_gen.cyclone

if [ -e "$1_gen.cyclone.smt2.dump" ]; then
  mv $1_gen.cyclone.smt2.dump $1_gen.smt2
  sed -i 's/simplify/assert/g' $1_gen.smt2
  echo "" >> $1_gen.smt2
  echo "(check-sat)" >> $1_gen.smt2
  echo "generated: $1_gen.smt2"
  rm -f $1_gen.cyclone
fi
